#!/usr/bin/env bash
# AUTO-GENERATED by orchestrator issue→test pipeline
# Source blocker: Ollama runner crashes on inference (exit -1): memory-constrained — Bazzite VM lo
# Generated at: 2026-05-09T16:20:48Z
set -euo pipefail
pass=0; fail=0
_pass(){ echo "PASS: $1 $2"; (( pass++ )) || true; }
_fail(){ echo "FAIL: $1 $2 — $3"; [[ -n "${4:-}" ]] && echo "FIX_CMD_$1: $4"; (( fail++ )) || true; }

# Auto-generated: Available RAM check
id=TSauto_oom
desc="Available RAM > 500MB (auto-generated)"
fix="pgrep -f research_loop.py | head -5 | xargs -r kill -STOP"
avail=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
if [[ "$avail" -gt 512000 ]]; then _pass "$id" "$desc (${avail}kB)"
else _fail "$id" "$desc" "only ${avail}kB available" "$fix"; fi

echo ""
echo "SYSTEM_TEST_RESULT: pass=$pass fail=$fail total=$((pass+fail))"
[[ "$fail" -eq 0 ]]
