#!/usr/bin/env bash
# AUTO-GENERATED by orchestrator issue→test pipeline
# Source blocker: self-test: FAIL: TS21 disk / usage < 90% — disk 92% >= 90%
# Generated at: 2026-05-10T09:09:09Z
set -euo pipefail
pass=0; fail=0
_pass(){ echo "PASS: $1 $2"; (( pass++ )) || true; }
_fail(){ echo "FAIL: $1 $2 — $3"; [[ -n "${4:-}" ]] && echo "FIX_CMD_$1: $4"; (( fail++ )) || true; }

# Auto-generated: Disk space check
id=TSauto_disk_space
desc="Disk / usage < 90% (auto-generated)"
fix="find /tmp -mtime +1 -delete 2>/dev/null; journalctl --vacuum-size=200M 2>/dev/null"
pct=$(df / | awk 'NR==2{gsub(/%/,""); print $5}')
if [[ "$pct" -lt 90 ]]; then _pass "$id" "$desc (${pct}%)"
else _fail "$id" "$desc" "${pct}% >= 90%" "$fix"; fi

echo ""
echo "SYSTEM_TEST_RESULT: pass=$pass fail=$fail total=$((pass+fail))"
[[ "$fail" -eq 0 ]]
